### ISSUE TITLE
It is showing 500 error page

### ISSUE THREAD

**Issue by PunitTailor55** [Newman101/BeeCTF#49]
I have done docker installation steps. When I launching the application on localhost it's showing 500 error page.

**Comment by Newman101** [comment]
Hi, thanks for notifying me regarding this. I might have missed something in documentation. I will check and fix it as soon as I can.

**Comment by PunitTailor55** [comment]
While installing dependencies it is showing 

```
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
```

**Comment by Newman101** [comment]
Hi @PunitTailor55, I'm still working on this. I got one error eliminated, just need to automate some bits and pieces and amend some documentation regarding the fixes I've made. Thanks for patience!

**Comment by Newman101** [comment]
Docker issue should be fixed now.

**Comment by Newman101** [comment]
Closing the issue for now, as Docker issue has been fixed. Thanks for reporting this!
